
name: workflow
on: push
jobs:
  runs-on: ubuntu-latest
  container: gradle:6-jdk11
  Clone-Down:
    name: Clone down repo
    steps:
    - uses: actions/chechout@v2
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
